@backend_HostAddress = http://localhost:5216

GET {{backend_HostAddress}}/weatherforecast/
Accept: application/json

###
### testing@testing.com Testing1!
### testAdmin@admin.com Testing1!
### testRandomUser@random.com Testing1!